AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hotel Management System API

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    MemorySize: 128

Resources:
  RegisterUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/                 
      Handler: users.register_user.register_user_handler
      Environment:
        Variables:
          POSTGRES_DB: hotel_management
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin123
          POSTGRES_HOST: host.docker.internal   
          POSTGRES_PORT: "5432"
      Events:
        RegisterAPI:
          Type: Api
          Properties:
            Path: /register
            Method: post

  LoginUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: users.login_user.login_user_handler
      Environment:
        Variables:
          POSTGRES_DB: hotel_management
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin123
          POSTGRES_HOST: host.docker.internal
          POSTGRES_PORT: "5432"
      Events:
        LoginAPI:
          Type: Api
          Properties:
            Path: /login
            Method: post

  CompleteProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: users.complete_profile.complete_profile_handler
      Environment:
        Variables:
          POSTGRES_DB: hotel_management
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin123
          POSTGRES_HOST: host.docker.internal
          POSTGRES_PORT: "5432"
      Events:
        LoginAPI:
          Type: Api
          Properties:
            Path: /complete-profile
            Method: post

    Metadata:
      BuildMethod: python3.12
      BuildProperties:
        IncludePaths:
          - users/
          - DB/
